version: '3.4'

services:
  nb.checkingaccount.api:
    image: checking-account:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_nb.checkingaccount.api$
    volumes:
      - C:\Git\Pessoal\CheckingAccount\NB.CheckingAccount\NB.CheckingAccount.API:/app
      - C:\Users\murilo.paxi\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_nb.checkingaccount.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_nb.checkingaccount.api$ bin/Debug/netcoreapp2.1/NB.CheckingAccount.API.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
